[env]
default_config_filename = "mise.local.toml"

[tools]
"github:boyter/cs" = "latest"
"github:psanford/wormhole-william" = { version = "latest", bin = "wormhole" }
"github:your-tools/ruplacer" = "latest"
