[env]
default_config_filename = "mise.toml"

[tools]
"github:boyter/cs" = "latest"
"github:psanford/wormhole-william" = { version = "latest", rename_exe = "wormhole" }
"github:your-tools/ruplacer" = "latest"

[settings]
experimental = true
python.uv_venv_auto = true
